<?php
/**
 *Configuração do WEGIA
*/
define( 'DB_NAME', 'wegia' );
define( 'DB_USER', 'wegiauser' );
define( 'DB_PASSWORD', 'senha' );
define( 'DB_HOST', 'localhost');
define( 'DB_CHARSET', 'utf8');
define( 'ROOT',dirname(__FILE__));
define( 'BKP_DIR', '/var/www/bkpWeGIA');
define( 'BACKUP_SIGNING_KEY_FILE', BKP_DIR . '/.backup_signing_private.pem');
define( 'WWW', 'https://demo.wegia.org/');
define('JWT_SECRET', 'your_jwt_secret_key_here');
define('ENV_APP', 'production');