<?php
/**
 *Configuração do WeGIA
*/
define( 'APP_TIMEZONE', 'America/Sao_Paulo');
define( 'CONTRIBUICOES_CRON_ID_PESSOA', 1);
define( 'BKP_DIR', '/var/www/bkpWeGIA');
define( 'BACKUP_SIGNING_KEY_FILE', BKP_DIR . '/.backup_signing_private.pem'); //gerador manual consulte: https://github.com/LabRedesCefetRJ/WeGIA/releases/tag/3.6.7
define( 'DB_NAME', 'wegia' );
define( 'DB_USER', 'wegiauser' );
define( 'DB_PASSWORD', 'senha' );
define( 'DB_HOST', 'localhost');
define( 'DB_CHARSET', 'utf8');
define( 'ROOT',dirname(__FILE__));
define( 'WWW', 'https://demo.wegia.org/');
define( 'SESSION_TIMEOUT', 1800); //30 minutos de inatividade antes de ser limpa pelo garbage collector

define( 'DEV_MODE', 'off');

/**
 *Configuração da API
*/

define('API_BASE_URL', 'https://demo.wegia.org/api/');
define('JWT_SECRET', 'your_jwt_secret_key_here'); //gerador manual: openssl rand -hex 32
define('ENV_APP', 'production'); //define('ENV_APP', 'development');

//Separe as origens permitidas com o caractere ","
define('CORS_ORIGIN', 'https://demo.wegia.org,http://localhost');
